//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemexControlIngreso_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST
    {
        public int Id { get; set; }
        public bool Llantas { get; set; }
        public bool Motor { get; set; }
        public bool Aceite { get; set; }
        public int IdViaje { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual VIAJE VIAJE { get; set; }
        public virtual VIAJECTRL VIAJECTRL { get; set; }
    }
}
