//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemexControlIngreso_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descanso
    {
        public int Id { get; set; }
        public int IdConductor { get; set; }
        public System.DateTime FechaDescanso { get; set; }
        public int IdViaje { get; set; }
        public string Estado { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        public virtual VIAJECTRL VIAJECTRL { get; set; }
    }
}
