//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemexControlIngreso_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public int Id { get; set; }
        public int IdRole { get; set; }
        public string Nombre { get; set; }
    
        public virtual USUARIOSROLE USUARIOSROLE { get; set; }
    }
}
