//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemexControlIngreso_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULOSRUTA
    {
        public int Id { get; set; }
        public string NumeroViaje { get; set; }
        public string Placa { get; set; }
        public string Trailer { get; set; }
        public string Conductor { get; set; }
        public string Celular { get; set; }
        public string Corredor { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime TiempoRestante { get; set; }
    }
}
