//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemexControlIngreso_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJE
    {
        public int IdViaje { get; set; }
        public int IdCorredor { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdConductor { get; set; }
        public Nullable<int> idPlaca { get; set; }
        public Nullable<int> idTrailer { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual CORREDOR CORREDOR { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        public virtual PLACAS PLACAS { get; set; }
        public virtual TRAILER TRAILER { get; set; }
    }
}
